version: 2
updates:
  - package-ecosystem: pip
    directory: /Backoffice
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /Backoffice
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /Website
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: pub
    directory: /MobileApp
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
