#!/usr/bin/env python3
"""
Email Setup Script for Humanitarian Databank
This script helps you configure Gmail for sending confirmation emails
"""

import getpass
import logging
import os
from pathlib import Path

logger = logging.getLogger(__name__)


def create_env_file():
    """Create a .env file with email configuration"""

    logger.info("Gmail Email Configuration Setup")
    logger.info("=" * 50)
    logger.info("")

    # Check if .env file already exists
    env_file = Path('.env')
    if env_file.exists():
        logger.warning(".env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ").lower()
        if response != 'y':
            logger.info("Setup cancelled.")
            return

    logger.info("Please provide your Gmail configuration:")
    logger.info("")

    # Get Gmail address
    while True:
        gmail = input("Enter your Gmail address: ").strip()
        if '@gmail.com' in gmail:
            break
        logger.error("Please enter a valid Gmail address (must contain @gmail.com)")

    logger.info("")
    logger.info("App Password Setup:")
    logger.info("You need to generate an App Password from Google:")
    logger.info("1. Go to https://myaccount.google.com/security")
    logger.info("2. Enable 2-Step Verification if not already enabled")
    logger.info("3. Go to 'App passwords' under 2-Step Verification")
    logger.info("4. Select 'Mail' as app and 'Other' as device")
    logger.info("5. Click 'Generate'")
    logger.info("6. Copy the 16-character password (remove spaces)")
    logger.info("")

    # Get App Password
    while True:
        app_password = getpass.getpass("Enter your Gmail App Password: ").strip()
        if len(app_password) >= 16:
            break
        logger.error("App Password should be 16 characters long")

    logger.info("")

    # Get admin emails
    admin_emails = input("Enter admin email(s) for notifications (comma-separated, or press Enter to use your Gmail): ").strip()
    if not admin_emails:
        admin_emails = gmail

    # Get base URL
    base_url = input("Enter your application base URL (or press Enter for http://localhost:5000): ").strip()
    if not base_url:
        base_url = "http://localhost:5000"

    # Create .env content
    env_content = f"""# Email Configuration for Humanitarian Databank
# Generated by setup_email.py

# Gmail Configuration
MAIL_USERNAME={gmail}
MAIL_PASSWORD={app_password}
MAIL_DEFAULT_SENDER={gmail}

# Admin Configuration
ADMIN_EMAILS={admin_emails}
BASE_URL={base_url}

# Application Configuration
# Set your API key for protected endpoints
API_KEY=your_api_key_here
SECRET_KEY=your_secret_key_here
"""

    # Write .env file
    try:
        with open('.env', 'w') as f:
            f.write(env_content)

        logger.info(".env file created successfully!")
        logger.info("")
        logger.info("Configuration Summary:")
        logger.info("   Gmail: %s", gmail)
        logger.info("   Admin emails: %s", admin_emails)
        logger.info("   Base URL: %s", base_url)
        logger.info("")
        logger.info("You can now test the email functionality with:")
        logger.info("   python test_email.py")
        logger.info("")
        logger.info("Important:")
        logger.info("   - Keep your .env file secure and don't commit it to version control")
        logger.info("   - The App Password is sensitive - don't share it")
        logger.info("   - For production, consider using a professional email service")

    except Exception as e:
        logger.error("Error creating .env file: %s", e)

def test_configuration():
    """Test the email configuration"""

    logger.info("Testing Email Configuration")
    logger.info("=" * 40)

    # Check if .env file exists
    if not Path('.env').exists():
        logger.error(".env file not found. Run setup first.")
        return

    # Check required environment variables
    required_vars = ['MAIL_USERNAME', 'MAIL_PASSWORD']
    missing_vars = []

    for var in required_vars:
        if not os.getenv(var):
            missing_vars.append(var)

    if missing_vars:
        logger.error("Missing environment variables: %s", ', '.join(missing_vars))
        logger.info("Please run the setup script first.")
        return

    logger.info("Environment variables found")
    logger.info("   Gmail: %s", os.getenv('MAIL_USERNAME'))
    logger.info("   Admin emails: %s", os.getenv('ADMIN_EMAILS', 'Not set'))
    logger.info("")

    # Ask if user wants to run the test
    response = input("Do you want to run the email test now? (y/N): ").lower()
    if response == 'y':
        logger.info("Running email test...")
        os.system('python test_email.py')
    else:
        logger.info("You can run the test later with: python test_email.py")

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    logger.info("Humanitarian Databank - Email Setup")
    logger.info("=" * 40)
    logger.info("")

    logger.info("Choose an option:")
    logger.info("1. Setup Gmail configuration")
    logger.info("2. Test existing configuration")
    logger.info("3. Exit")
    logger.info("")

    choice = input("Enter your choice (1-3): ").strip()

    if choice == '1':
        create_env_file()
    elif choice == '2':
        test_configuration()
    elif choice == '3':
        logger.info("Goodbye!")
    else:
        logger.warning("Invalid choice. Please run the script again.")
