"""add short_name to country

Revision ID: 2724a30cb756
Revises: add_source_url_ai_docs
Create Date: 2026-02-02 11:16:36.255186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2724a30cb756'
down_revision = 'add_source_url_ai_docs'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_conversation', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_conversation_last_message_at')

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.drop_constraint('fk_form_template_published_version', type_='foreignkey')
        batch_op.create_foreign_key('fk_form_template_published_version', 'form_template_version', ['published_version_id'], ['id'], ondelete='SET NULL', initially='DEFERRED', deferrable=True, use_alter=True)

    with op.batch_alter_table('rbac_access_grant', schema=None) as batch_op:
        batch_op.drop_index('uq_rbac_access_grant_assignment', postgresql_where="((scope_kind)::text = 'assignment'::text)")
        batch_op.drop_index('uq_rbac_access_grant_entity', postgresql_where="((scope_kind)::text = 'entity'::text)")
        batch_op.drop_index('uq_rbac_access_grant_global', postgresql_where="((scope_kind)::text = 'global'::text)")
        batch_op.drop_index('uq_rbac_access_grant_template', postgresql_where="((scope_kind)::text = 'template'::text)")

    with op.batch_alter_table('rbac_permission', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rbac_permission_code', type_='unique')
        batch_op.drop_index('ix_rbac_permission_code')
        batch_op.create_index(batch_op.f('ix_rbac_permission_code'), ['code'], unique=True)

    with op.batch_alter_table('rbac_role', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rbac_role_code', type_='unique')
        batch_op.drop_index('ix_rbac_role_code')
        batch_op.create_index(batch_op.f('ix_rbac_role_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rbac_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rbac_role_code'))
        batch_op.create_index('ix_rbac_role_code', ['code'], unique=False)
        batch_op.create_unique_constraint('uq_rbac_role_code', ['code'])

    with op.batch_alter_table('rbac_permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rbac_permission_code'))
        batch_op.create_index('ix_rbac_permission_code', ['code'], unique=False)
        batch_op.create_unique_constraint('uq_rbac_permission_code', ['code'])

    with op.batch_alter_table('rbac_access_grant', schema=None) as batch_op:
        batch_op.create_index('uq_rbac_access_grant_template', ['principal_type', 'principal_id', 'permission_id', 'template_id'], unique=True, postgresql_where="((scope_kind)::text = 'template'::text)")
        batch_op.create_index('uq_rbac_access_grant_global', ['principal_type', 'principal_id', 'permission_id'], unique=True, postgresql_where="((scope_kind)::text = 'global'::text)")
        batch_op.create_index('uq_rbac_access_grant_entity', ['principal_type', 'principal_id', 'permission_id', 'entity_type', 'entity_id'], unique=True, postgresql_where="((scope_kind)::text = 'entity'::text)")
        batch_op.create_index('uq_rbac_access_grant_assignment', ['principal_type', 'principal_id', 'permission_id', 'assigned_form_id'], unique=True, postgresql_where="((scope_kind)::text = 'assignment'::text)")

    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.drop_constraint('fk_form_template_published_version', type_='foreignkey')
        batch_op.create_foreign_key('fk_form_template_published_version', 'form_template_version', ['published_version_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_column('short_name')

    with op.batch_alter_table('ai_conversation', schema=None) as batch_op:
        batch_op.create_index('ix_ai_conversation_last_message_at', ['last_message_at'], unique=False)

    # ### end Alembic commands ###
