"""Initial db

Revision ID: 90aafe7711e0
Revises:
Create Date: 2025-11-19 20:19:35.202230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90aafe7711e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_endpoint', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=15), nullable=False),
    sa.Column('partof', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('name_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso2'),
    sa.UniqueConstraint('iso3'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('can_manage_users', sa.Boolean(), nullable=False),
    sa.Column('can_manage_templates', sa.Boolean(), nullable=False),
    sa.Column('can_manage_assignments', sa.Boolean(), nullable=False),
    sa.Column('can_manage_countries', sa.Boolean(), nullable=False),
    sa.Column('can_manage_publications', sa.Boolean(), nullable=False),
    sa.Column('can_manage_indicator_bank', sa.Boolean(), nullable=False),
    sa.Column('can_manage_settings', sa.Boolean(), nullable=False),
    sa.Column('can_view_analytics', sa.Boolean(), nullable=False),
    sa.Column('can_manage_public_assignments', sa.Boolean(), nullable=False),
    sa.Column('can_view_admin_dashboard', sa.Boolean(), nullable=False),
    sa.Column('can_view_audit_trail', sa.Boolean(), nullable=False),
    sa.Column('can_manage_api', sa.Boolean(), nullable=False),
    sa.Column('can_manage_plugins', sa.Boolean(), nullable=False),
    sa.Column('chatbot_enabled', sa.Boolean(), nullable=False),
    sa.Column('profile_color', sa.String(length=7), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
    op.create_table('form_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('owned_by', sa.Integer(), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('add_to_self_report', sa.Boolean(), nullable=False),
    sa.Column('display_order_visible', sa.Boolean(), nullable=False),
    sa.Column('is_paginated', sa.Boolean(), nullable=False),
    sa.Column('enable_export_pdf', sa.Boolean(), nullable=False),
    sa.Column('enable_export_excel', sa.Boolean(), nullable=False),
    sa.Column('enable_import_excel', sa.Boolean(), nullable=False),
    sa.Column('name_translations', sa.JSON(), nullable=True),
    sa.Column('published_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owned_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.create_index('ix_form_template_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_form_template_is_paginated', ['is_paginated'], unique=False)
        batch_op.create_index('ix_form_template_owned_by', ['owned_by'], unique=False)
        batch_op.create_index('ix_form_template_type', ['template_type'], unique=False)

    op.create_table('form_template_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('based_on_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['based_on_version_id'], ['form_template_version.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['form_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version_number', name='uq_template_version_number')
    )
    with op.batch_alter_table('form_template_version', schema=None) as batch_op:
        batch_op.create_index('ix_form_template_version_template_status', ['template_id', 'status'], unique=False)

    # Add foreign key constraint for published_version_id after form_template_version is created
    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_form_template_published_version', 'form_template_version', ['published_version_id'], ['id'], ondelete='SET NULL')

    op.create_table('indicator_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('name_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('definition_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('emergency', sa.Boolean(), nullable=False),
    sa.Column('related_programs', sa.Text(), nullable=True),
    sa.Column('sector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sub_sector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('indicator_bank', schema=None) as batch_op:
        batch_op.create_index('ix_indicator_bank_archived', ['archived'], unique=False)
        batch_op.create_index('ix_indicator_bank_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_indicator_bank_emergency', ['emergency'], unique=False)
        batch_op.create_index('ix_indicator_bank_type_unit', ['type', 'unit'], unique=False)
        batch_op.create_index('ix_indicator_bank_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_indicator_bank_usage_count', ['usage_count'], unique=False)

    op.create_table('lookup_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('columns_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('lookup_list', schema=None) as batch_op:
        batch_op.create_index('ix_lookup_list_updated_at', ['updated_at'], unique=False)

    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('default_title', sa.String(length=255), nullable=False),
    sa.Column('default_description', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.create_index('ix_resource_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_resource_pub_date', ['publication_date'], unique=False)
        batch_op.create_index('ix_resource_type', ['resource_type'], unique=False)

    op.create_table('secretariat_divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('secretariat_regional_offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('logo_path', sa.String(length=512), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon_class', sa.String(length=50), nullable=True),
    sa.Column('name_french', sa.String(length=100), nullable=True),
    sa.Column('name_spanish', sa.String(length=100), nullable=True),
    sa.Column('name_arabic', sa.String(length=100), nullable=True),
    sa.Column('name_chinese', sa.String(length=100), nullable=True),
    sa.Column('name_russian', sa.String(length=100), nullable=True),
    sa.Column('name_hindi', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.create_index('ix_sector_active_order', ['is_active', 'display_order'], unique=False)

    op.create_table('admin_action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_description', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_action_log', schema=None) as batch_op:
        batch_op.create_index('ix_admin_action_risk', ['risk_level'], unique=False)
        batch_op.create_index('ix_admin_action_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index('ix_admin_action_type', ['action_type'], unique=False)
        batch_op.create_index('ix_admin_action_user_time', ['admin_user_id', 'timestamp'], unique=False)

    op.create_table('assigned_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('period_name', sa.String(length=100), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('unique_token', sa.String(length=36), nullable=True),
    sa.Column('is_public_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['form_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_token')
    )
    with op.batch_alter_table('assigned_form', schema=None) as batch_op:
        batch_op.create_index('ix_assigned_form_assigned_at', ['assigned_at'], unique=False)
        batch_op.create_index('ix_assigned_form_public_active', ['is_public_active'], unique=False)
        batch_op.create_index('ix_assigned_form_public_token', ['unique_token'], unique=False)
        batch_op.create_index('ix_assigned_form_template_period', ['template_id', 'period_name'], unique=False)

    op.create_table('common_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('meaning_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('common_word', schema=None) as batch_op:
        batch_op.create_index('ix_common_word_active', ['is_active'], unique=False)
        batch_op.create_index('ix_common_word_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_common_word_created_by', ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_common_word_term'), ['term'], unique=True)

    op.create_table('country_access_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('request_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['processed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'country_id', 'status', name='uq_user_country_status_active')
    )
    with op.batch_alter_table('country_access_request', schema=None) as batch_op:
        batch_op.create_index('ix_car_status_time', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_car_user', ['user_id'], unique=False)

    op.create_table('entity_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_description', sa.Text(), nullable=False),
    sa.Column('summary_key', sa.String(length=255), nullable=False),
    sa.Column('summary_params', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('related_object_type', sa.String(length=50), nullable=True),
    sa.Column('related_object_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('related_url', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('activity_category', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_activity_log', schema=None) as batch_op:
        batch_op.create_index('ix_entity_activity_assignment', ['assignment_id'], unique=False)
        batch_op.create_index('ix_entity_activity_category', ['activity_category'], unique=False)
        batch_op.create_index('ix_entity_activity_country_time', ['country_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_entity_activity_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_entity_activity_entity_time', ['entity_type', 'entity_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_entity_activity_type', ['activity_type'], unique=False)
        batch_op.create_index('ix_entity_activity_user_time', ['user_id', 'timestamp'], unique=False)

    op.create_table('form_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name_translations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['form_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['form_template_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_page', schema=None) as batch_op:
        batch_op.create_index('ix_form_page_template_order', ['template_id', 'order'], unique=False)
        batch_op.create_index('ix_form_page_version', ['version_id'], unique=False)

    op.create_table('indicator_bank_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_bank_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('name_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('definition_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('emergency', sa.Boolean(), nullable=False),
    sa.Column('related_programs', sa.Text(), nullable=True),
    sa.Column('sector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sub_sector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_bank_id'], ['indicator_bank.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indicator_bank_history', schema=None) as batch_op:
        batch_op.create_index('ix_indicator_history_change_type', ['change_type'], unique=False)
        batch_op.create_index('ix_indicator_history_indicator_time', ['indicator_bank_id', 'created_at'], unique=False)
        batch_op.create_index('ix_indicator_history_user', ['user_id'], unique=False)

    op.create_table('indicator_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter_name', sa.String(length=255), nullable=False),
    sa.Column('submitter_email', sa.String(length=255), nullable=False),
    sa.Column('suggestion_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('indicator_id', sa.Integer(), nullable=True),
    sa.Column('indicator_name', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('sector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sub_sector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emergency', sa.Boolean(), nullable=False),
    sa.Column('related_programs', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator_bank.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indicator_suggestion', schema=None) as batch_op:
        batch_op.create_index('ix_indicator_suggestion_indicator', ['indicator_id'], unique=False)
        batch_op.create_index('ix_indicator_suggestion_reviewer', ['reviewed_by_user_id'], unique=False)
        batch_op.create_index('ix_indicator_suggestion_status', ['status'], unique=False)
        batch_op.create_index('ix_indicator_suggestion_submitted_at', ['submitted_at'], unique=False)
        batch_op.create_index('ix_indicator_suggestion_submitter_email', ['submitter_email'], unique=False)

    op.create_table('lookup_list_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lookup_list_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lookup_list_id'], ['lookup_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lookup_list_id', 'order', name='_lookup_list_row_order_uc')
    )
    with op.batch_alter_table('lookup_list_row', schema=None) as batch_op:
        batch_op.create_index('ix_lookup_list_row_list_order', ['lookup_list_id', 'order'], unique=False)

    op.create_table('national_societies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.Enum('assignment_created', 'assignment_submitted', 'assignment_approved', 'assignment_reopened', 'public_submission_received', 'form_updated', 'document_uploaded', 'user_added_to_country', 'template_updated', 'self_report_created', 'deadline_reminder', 'admin_message', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_object_type', sa.String(length=50), nullable=True),
    sa.Column('related_object_id', sa.Integer(), nullable=True),
    sa.Column('related_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('notification_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.String(length=64), nullable=True),
    sa.Column('action_buttons', sa.JSON(), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('action_taken_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_archived', ['is_archived'], unique=False)
        batch_op.create_index('ix_notification_country', ['country_id'], unique=False)
        batch_op.create_index('ix_notification_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_notification_group', ['group_id'], unique=False)
        batch_op.create_index('ix_notification_hash', ['notification_hash'], unique=False)
        batch_op.create_index('ix_notification_is_read', ['is_read'], unique=False)
        batch_op.create_index('ix_notification_priority', ['priority'], unique=False)
        batch_op.create_index('ix_notification_type', ['notification_type'], unique=False)
        batch_op.create_index('ix_notification_user_time', ['user_id', 'created_at'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('notification_types_enabled', sa.JSON(), nullable=False),
    sa.Column('notification_frequency', sa.String(length=20), nullable=False),
    sa.Column('digest_day', sa.String(length=10), nullable=True),
    sa.Column('digest_time', sa.String(length=10), nullable=True),
    sa.Column('sound_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notification_types_enabled', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ns_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('coordinates', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('resource_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_relative_path', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_filename', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_relative_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'language_code', name='_resource_language_uc')
    )
    with op.batch_alter_table('resource_translation', schema=None) as batch_op:
        batch_op.create_index('ix_resource_tr_lang', ['language_code'], unique=False)

    op.create_table('secretariat_cluster_offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('regional_office_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['regional_office_id'], ['secretariat_regional_offices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('secretariat_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['secretariat_divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_event', schema=None) as batch_op:
        batch_op.create_index('ix_security_event_resolved', ['is_resolved'], unique=False)
        batch_op.create_index('ix_security_event_resolved_by', ['resolved_by_user_id'], unique=False)
        batch_op.create_index('ix_security_event_severity', ['severity'], unique=False)
        batch_op.create_index('ix_security_event_type', ['event_type'], unique=False)
        batch_op.create_index('ix_security_event_user_time', ['user_id', 'timestamp'], unique=False)

    op.create_table('sub_sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('logo_path', sa.String(length=512), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon_class', sa.String(length=50), nullable=True),
    sa.Column('name_french', sa.String(length=100), nullable=True),
    sa.Column('name_spanish', sa.String(length=100), nullable=True),
    sa.Column('name_arabic', sa.String(length=100), nullable=True),
    sa.Column('name_chinese', sa.String(length=100), nullable=True),
    sa.Column('name_russian', sa.String(length=100), nullable=True),
    sa.Column('name_hindi', sa.String(length=100), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('sub_sector', schema=None) as batch_op:
        batch_op.create_index('ix_subsector_active_order', ['is_active', 'display_order'], unique=False)
        batch_op.create_index('ix_subsector_sector', ['sector_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index('ix_system_settings_key', ['setting_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_settings_setting_key'), ['setting_key'], unique=True)

    op.create_table('template_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=True),
    sa.Column('shared_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['form_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'shared_with_user_id', name='uq_template_share_template_user')
    )
    with op.batch_alter_table('template_share', schema=None) as batch_op:
        batch_op.create_index('ix_template_share_template_user', ['template_id', 'shared_with_user_id'], unique=False)
        batch_op.create_index('ix_template_share_user', ['shared_with_user_id'], unique=False)

    op.create_table('user_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('url_path', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token'),
    sa.UniqueConstraint('device_token', name='uq_user_device_token')
    )
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.create_index('ix_user_device_platform', ['platform'], unique=False)
        batch_op.create_index('ix_user_device_token', ['device_token'], unique=False)
        batch_op.create_index('ix_user_device_user', ['user_id'], unique=False)

    op.create_table('user_entity_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', name='_user_entity_uc')
    )
    with op.batch_alter_table('user_entity_permissions', schema=None) as batch_op:
        batch_op.create_index('ix_user_entity_type_id', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_user_entity_user', ['user_id'], unique=False)

    op.create_table('user_login_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_attempted', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts_count', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('is_bot_detected', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('referrer_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_session_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('session_start', sa.DateTime(), nullable=False),
    sa.Column('session_end', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('actions_performed', sa.Integer(), nullable=False),
    sa.Column('forms_submitted', sa.Integer(), nullable=False),
    sa.Column('files_uploaded', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ended_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('assignment_entity_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assigned_form_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('status_timestamp', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('is_public_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_form_id'], ['assigned_form.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assigned_form_id', 'entity_type', 'entity_id', name='_assigned_entity_uc')
    )
    with op.batch_alter_table('assignment_entity_status', schema=None) as batch_op:
        batch_op.create_index('ix_aes_assigned_form', ['assigned_form_id'], unique=False)
        batch_op.create_index('ix_aes_due_date', ['due_date'], unique=False)
        batch_op.create_index('ix_aes_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_aes_is_public_available', ['is_public_available'], unique=False)
        batch_op.create_index('ix_aes_status', ['status'], unique=False)
        batch_op.create_index('ix_aes_status_timestamp', ['status_timestamp'], unique=False)

    op.create_table('email_delivery_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_delivery_log', schema=None) as batch_op:
        batch_op.create_index('ix_email_delivery_retry', ['next_retry_at'], unique=False)
        batch_op.create_index('ix_email_delivery_status', ['status'], unique=False)
        batch_op.create_index('ix_email_delivery_user', ['user_id'], unique=False)

    op.create_table('form_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Float(), nullable=False),
    sa.Column('parent_section_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('max_dynamic_indicators', sa.Integer(), nullable=True),
    sa.Column('allowed_sectors', sa.JSON(), nullable=True),
    sa.Column('indicator_filters', sa.JSON(), nullable=True),
    sa.Column('allow_data_not_available', sa.Boolean(), nullable=False),
    sa.Column('allow_not_applicable', sa.Boolean(), nullable=False),
    sa.Column('allowed_disaggregation_options', sa.JSON(), nullable=True),
    sa.Column('data_entry_display_filters', sa.JSON(), nullable=True),
    sa.Column('add_indicator_note', sa.Text(), nullable=True),
    sa.Column('name_translations', sa.JSON(), nullable=True),
    sa.Column('relevance_condition', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['form_page.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_section_id'], ['form_section.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['form_template.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['form_template_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_section', schema=None) as batch_op:
        batch_op.create_index('ix_form_section_page', ['page_id'], unique=False)
        batch_op.create_index('ix_form_section_parent', ['parent_section_id'], unique=False)
        batch_op.create_index('ix_form_section_template_order', ['template_id', 'order'], unique=False)
        batch_op.create_index('ix_form_section_type', ['section_type'], unique=False)
        batch_op.create_index('ix_form_section_version', ['version_id'], unique=False)

    op.create_table('ns_subbranches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('coordinates', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['ns_branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('public_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assigned_form_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='publicsubmissionstatus'), nullable=False),
    sa.Column('submitter_name', sa.String(length=255), nullable=True),
    sa.Column('submitter_email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['assigned_form_id'], ['assigned_form.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('public_submission', schema=None) as batch_op:
        batch_op.create_index('ix_public_submission_assigned_country', ['assigned_form_id', 'country_id'], unique=False)
        batch_op.create_index('ix_public_submission_status', ['status'], unique=False)
        batch_op.create_index('ix_public_submission_submitted_at', ['submitted_at'], unique=False)
        batch_op.create_index('ix_public_submission_submitter_email', ['submitter_email'], unique=False)

    op.create_table('dynamic_indicator_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_entity_status_id', sa.Integer(), nullable=True),
    sa.Column('public_submission_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('indicator_bank_id', sa.Integer(), nullable=False),
    sa.Column('custom_label', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Float(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('disagg_data', sa.JSON(), nullable=True),
    sa.Column('data_not_available', sa.Boolean(), nullable=True),
    sa.Column('not_applicable', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assignment_entity_status_id'], ['assignment_entity_status.id'], ),
    sa.ForeignKeyConstraint(['indicator_bank_id'], ['indicator_bank.id'], ),
    sa.ForeignKeyConstraint(['public_submission_id'], ['public_submission.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['form_section.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_entity_status_id', 'section_id', 'indicator_bank_id', name='_dynamic_indicator_entity_unique'),
    sa.UniqueConstraint('public_submission_id', 'section_id', 'indicator_bank_id', name='_dynamic_indicator_public_unique')
    )
    with op.batch_alter_table('dynamic_indicator_data', schema=None) as batch_op:
        batch_op.create_index('ix_dynamic_indicator_added_at', ['added_at'], unique=False)
        batch_op.create_index('ix_dynamic_indicator_added_by', ['added_by_user_id'], unique=False)
        batch_op.create_index('ix_dynamic_indicator_aes', ['assignment_entity_status_id'], unique=False)
        batch_op.create_index('ix_dynamic_indicator_public', ['public_submission_id'], unique=False)
        batch_op.create_index('ix_dynamic_indicator_section', ['section_id'], unique=False)

    op.create_table('form_item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('order', sa.Float(), nullable=False),
    sa.Column('relevance_condition', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('indicator_bank_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('validation_condition', sa.Text(), nullable=True),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('lookup_list_id', sa.String(length=50), nullable=True),
    sa.Column('list_display_column', sa.String(length=100), nullable=True),
    sa.Column('list_filters_json', sa.JSON(), nullable=True),
    sa.Column('label_translations', sa.JSON(), nullable=True),
    sa.Column('definition_translations', sa.JSON(), nullable=True),
    sa.Column('options_translations', sa.JSON(), nullable=True),
    sa.Column('description_translations', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_bank_id'], ['indicator_bank.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['form_section.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['form_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['form_template_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    with op.batch_alter_table('form_item', schema=None) as batch_op:
        batch_op.create_index('ix_form_item_indicator_bank', ['indicator_bank_id'], unique=False)
        batch_op.create_index('ix_form_item_item_type', ['item_type'], unique=False)
        batch_op.create_index('ix_form_item_lookup_list', ['lookup_list_id'], unique=False)
        batch_op.create_index('ix_form_item_section_order', ['section_id', 'order'], unique=False)
        batch_op.create_index('ix_form_item_template_order', ['template_id', 'order'], unique=False)
        batch_op.create_index('ix_form_item_version', ['version_id'], unique=False)

    op.create_table('ns_localunits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('coordinates', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('subbranch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['ns_branches.id'], ),
    sa.ForeignKeyConstraint(['subbranch_id'], ['ns_subbranches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repeat_group_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_entity_status_id', sa.Integer(), nullable=True),
    sa.Column('public_submission_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('instance_number', sa.Integer(), nullable=False),
    sa.Column('instance_label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_entity_status_id'], ['assignment_entity_status.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['public_submission_id'], ['public_submission.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['form_section.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_entity_status_id', 'section_id', 'instance_number', name='_repeat_instance_entity_unique'),
    sa.UniqueConstraint('public_submission_id', 'section_id', 'instance_number', name='_repeat_instance_public_unique')
    )
    with op.batch_alter_table('repeat_group_instance', schema=None) as batch_op:
        batch_op.create_index('ix_repeat_instance_aes', ['assignment_entity_status_id'], unique=False)
        batch_op.create_index('ix_repeat_instance_created_by', ['created_by_user_id'], unique=False)
        batch_op.create_index('ix_repeat_instance_label', ['instance_label'], unique=False)
        batch_op.create_index('ix_repeat_instance_public', ['public_submission_id'], unique=False)
        batch_op.create_index('ix_repeat_instance_section', ['section_id'], unique=False)

    op.create_table('form_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_entity_status_id', sa.Integer(), nullable=True),
    sa.Column('public_submission_id', sa.Integer(), nullable=True),
    sa.Column('form_item_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('disagg_data', sa.JSON(), nullable=True),
    sa.Column('data_not_available', sa.Boolean(), nullable=True),
    sa.Column('not_applicable', sa.Boolean(), nullable=True),
    sa.Column('prefilled_value', sa.JSON(), nullable=True),
    sa.Column('imputed_value', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_entity_status_id'], ['assignment_entity_status.id'], ),
    sa.ForeignKeyConstraint(['form_item_id'], ['form_item.item_id'], ),
    sa.ForeignKeyConstraint(['public_submission_id'], ['public_submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.create_index('ix_form_data_aes_item', ['assignment_entity_status_id', 'form_item_id'], unique=False)
        batch_op.create_index('ix_form_data_form_item', ['form_item_id'], unique=False)
        batch_op.create_index('ix_form_data_public_item', ['public_submission_id', 'form_item_id'], unique=False)
        batch_op.create_index('ix_form_data_submitted_at', ['submitted_at'], unique=False)

    op.create_table('repeat_group_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repeat_instance_id', sa.Integer(), nullable=False),
    sa.Column('form_item_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('disagg_data', sa.JSON(), nullable=True),
    sa.Column('data_not_available', sa.Boolean(), nullable=True),
    sa.Column('not_applicable', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_item_id'], ['form_item.item_id'], ),
    sa.ForeignKeyConstraint(['repeat_instance_id'], ['repeat_group_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repeat_group_data', schema=None) as batch_op:
        batch_op.create_index('ix_repeat_data_form_item', ['form_item_id'], unique=False)
        batch_op.create_index('ix_repeat_data_instance', ['repeat_instance_id'], unique=False)
        batch_op.create_index('ix_repeat_data_instance_item', ['repeat_instance_id', 'form_item_id'], unique=False)
        batch_op.create_index('ix_repeat_data_submitted_at', ['submitted_at'], unique=False)

    op.create_table('submitted_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_entity_status_id', sa.Integer(), nullable=True),
    sa.Column('public_submission_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('form_item_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('thumbnail_filename', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_relative_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['assignment_entity_status_id'], ['assignment_entity_status.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['form_item_id'], ['form_item.item_id'], ),
    sa.ForeignKeyConstraint(['public_submission_id'], ['public_submission.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submitted_document', schema=None) as batch_op:
        batch_op.create_index('ix_submitted_doc_aes', ['assignment_entity_status_id'], unique=False)
        batch_op.create_index('ix_submitted_doc_country', ['country_id'], unique=False)
        batch_op.create_index('ix_submitted_doc_is_public', ['is_public'], unique=False)
        batch_op.create_index('ix_submitted_doc_item', ['form_item_id'], unique=False)
        batch_op.create_index('ix_submitted_doc_language', ['language'], unique=False)
        batch_op.create_index('ix_submitted_doc_public', ['public_submission_id'], unique=False)
        batch_op.create_index('ix_submitted_doc_status', ['status'], unique=False)
        batch_op.create_index('ix_submitted_doc_uploaded_at', ['uploaded_at'], unique=False)
        batch_op.create_index('ix_submitted_doc_uploaded_by', ['uploaded_by_user_id'], unique=False)
        batch_op.create_index('ix_submitted_doc_year', ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitted_document', schema=None) as batch_op:
        batch_op.drop_index('ix_submitted_doc_year')
        batch_op.drop_index('ix_submitted_doc_uploaded_by')
        batch_op.drop_index('ix_submitted_doc_uploaded_at')
        batch_op.drop_index('ix_submitted_doc_status')
        batch_op.drop_index('ix_submitted_doc_public')
        batch_op.drop_index('ix_submitted_doc_language')
        batch_op.drop_index('ix_submitted_doc_item')
        batch_op.drop_index('ix_submitted_doc_is_public')
        batch_op.drop_index('ix_submitted_doc_country')
        batch_op.drop_index('ix_submitted_doc_aes')

    op.drop_table('submitted_document')
    with op.batch_alter_table('repeat_group_data', schema=None) as batch_op:
        batch_op.drop_index('ix_repeat_data_submitted_at')
        batch_op.drop_index('ix_repeat_data_instance_item')
        batch_op.drop_index('ix_repeat_data_instance')
        batch_op.drop_index('ix_repeat_data_form_item')

    op.drop_table('repeat_group_data')
    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.drop_index('ix_form_data_submitted_at')
        batch_op.drop_index('ix_form_data_public_item')
        batch_op.drop_index('ix_form_data_form_item')
        batch_op.drop_index('ix_form_data_aes_item')

    op.drop_table('form_data')
    with op.batch_alter_table('repeat_group_instance', schema=None) as batch_op:
        batch_op.drop_index('ix_repeat_instance_section')
        batch_op.drop_index('ix_repeat_instance_public')
        batch_op.drop_index('ix_repeat_instance_label')
        batch_op.drop_index('ix_repeat_instance_created_by')
        batch_op.drop_index('ix_repeat_instance_aes')

    op.drop_table('repeat_group_instance')
    op.drop_table('ns_localunits')
    with op.batch_alter_table('form_item', schema=None) as batch_op:
        batch_op.drop_index('ix_form_item_version')
        batch_op.drop_index('ix_form_item_template_order')
        batch_op.drop_index('ix_form_item_section_order')
        batch_op.drop_index('ix_form_item_lookup_list')
        batch_op.drop_index('ix_form_item_item_type')
        batch_op.drop_index('ix_form_item_indicator_bank')

    op.drop_table('form_item')
    with op.batch_alter_table('dynamic_indicator_data', schema=None) as batch_op:
        batch_op.drop_index('ix_dynamic_indicator_section')
        batch_op.drop_index('ix_dynamic_indicator_public')
        batch_op.drop_index('ix_dynamic_indicator_aes')
        batch_op.drop_index('ix_dynamic_indicator_added_by')
        batch_op.drop_index('ix_dynamic_indicator_added_at')

    op.drop_table('dynamic_indicator_data')
    with op.batch_alter_table('public_submission', schema=None) as batch_op:
        batch_op.drop_index('ix_public_submission_submitter_email')
        batch_op.drop_index('ix_public_submission_submitted_at')
        batch_op.drop_index('ix_public_submission_status')
        batch_op.drop_index('ix_public_submission_assigned_country')

    op.drop_table('public_submission')
    op.drop_table('ns_subbranches')
    with op.batch_alter_table('form_section', schema=None) as batch_op:
        batch_op.drop_index('ix_form_section_version')
        batch_op.drop_index('ix_form_section_type')
        batch_op.drop_index('ix_form_section_template_order')
        batch_op.drop_index('ix_form_section_parent')
        batch_op.drop_index('ix_form_section_page')

    op.drop_table('form_section')
    with op.batch_alter_table('email_delivery_log', schema=None) as batch_op:
        batch_op.drop_index('ix_email_delivery_user')
        batch_op.drop_index('ix_email_delivery_status')
        batch_op.drop_index('ix_email_delivery_retry')

    op.drop_table('email_delivery_log')
    with op.batch_alter_table('assignment_entity_status', schema=None) as batch_op:
        batch_op.drop_index('ix_aes_status_timestamp')
        batch_op.drop_index('ix_aes_status')
        batch_op.drop_index('ix_aes_is_public_available')
        batch_op.drop_index('ix_aes_entity')
        batch_op.drop_index('ix_aes_due_date')
        batch_op.drop_index('ix_aes_assigned_form')

    op.drop_table('assignment_entity_status')
    op.drop_table('user_session_log')
    op.drop_table('user_login_log')
    with op.batch_alter_table('user_entity_permissions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_entity_user')
        batch_op.drop_index('ix_user_entity_type_id')

    op.drop_table('user_entity_permissions')
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.drop_index('ix_user_device_user')
        batch_op.drop_index('ix_user_device_token')
        batch_op.drop_index('ix_user_device_platform')

    op.drop_table('user_devices')
    op.drop_table('user_activity_log')
    with op.batch_alter_table('template_share', schema=None) as batch_op:
        batch_op.drop_index('ix_template_share_user')
        batch_op.drop_index('ix_template_share_template_user')

    op.drop_table('template_share')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_setting_key'))
        batch_op.drop_index('ix_system_settings_key')

    op.drop_table('system_settings')
    with op.batch_alter_table('sub_sector', schema=None) as batch_op:
        batch_op.drop_index('ix_subsector_sector')
        batch_op.drop_index('ix_subsector_active_order')

    op.drop_table('sub_sector')
    with op.batch_alter_table('security_event', schema=None) as batch_op:
        batch_op.drop_index('ix_security_event_user_time')
        batch_op.drop_index('ix_security_event_type')
        batch_op.drop_index('ix_security_event_severity')
        batch_op.drop_index('ix_security_event_resolved_by')
        batch_op.drop_index('ix_security_event_resolved')

    op.drop_table('security_event')
    op.drop_table('secretariat_departments')
    op.drop_table('secretariat_cluster_offices')
    with op.batch_alter_table('resource_translation', schema=None) as batch_op:
        batch_op.drop_index('ix_resource_tr_lang')

    op.drop_table('resource_translation')
    op.drop_table('ns_branches')
    op.drop_table('notification_preferences')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_user_time')
        batch_op.drop_index('ix_notification_type')
        batch_op.drop_index('ix_notification_priority')
        batch_op.drop_index('ix_notification_is_read')
        batch_op.drop_index('ix_notification_hash')
        batch_op.drop_index('ix_notification_group')
        batch_op.drop_index('ix_notification_expires')
        batch_op.drop_index('ix_notification_country')
        batch_op.drop_index('ix_notification_archived')

    op.drop_table('notification')
    op.drop_table('national_societies')
    with op.batch_alter_table('lookup_list_row', schema=None) as batch_op:
        batch_op.drop_index('ix_lookup_list_row_list_order')

    op.drop_table('lookup_list_row')
    with op.batch_alter_table('indicator_suggestion', schema=None) as batch_op:
        batch_op.drop_index('ix_indicator_suggestion_submitter_email')
        batch_op.drop_index('ix_indicator_suggestion_submitted_at')
        batch_op.drop_index('ix_indicator_suggestion_status')
        batch_op.drop_index('ix_indicator_suggestion_reviewer')
        batch_op.drop_index('ix_indicator_suggestion_indicator')

    op.drop_table('indicator_suggestion')
    with op.batch_alter_table('indicator_bank_history', schema=None) as batch_op:
        batch_op.drop_index('ix_indicator_history_user')
        batch_op.drop_index('ix_indicator_history_indicator_time')
        batch_op.drop_index('ix_indicator_history_change_type')

    op.drop_table('indicator_bank_history')
    with op.batch_alter_table('form_page', schema=None) as batch_op:
        batch_op.drop_index('ix_form_page_version')
        batch_op.drop_index('ix_form_page_template_order')

    op.drop_table('form_page')
    with op.batch_alter_table('entity_activity_log', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_activity_user_time')
        batch_op.drop_index('ix_entity_activity_type')
        batch_op.drop_index('ix_entity_activity_entity_time')
        batch_op.drop_index('ix_entity_activity_entity')
        batch_op.drop_index('ix_entity_activity_country_time')
        batch_op.drop_index('ix_entity_activity_category')
        batch_op.drop_index('ix_entity_activity_assignment')

    op.drop_table('entity_activity_log')
    with op.batch_alter_table('country_access_request', schema=None) as batch_op:
        batch_op.drop_index('ix_car_user')
        batch_op.drop_index('ix_car_status_time')

    op.drop_table('country_access_request')
    with op.batch_alter_table('common_word', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_common_word_term'))
        batch_op.drop_index('ix_common_word_created_by')
        batch_op.drop_index('ix_common_word_created_at')
        batch_op.drop_index('ix_common_word_active')

    op.drop_table('common_word')
    with op.batch_alter_table('assigned_form', schema=None) as batch_op:
        batch_op.drop_index('ix_assigned_form_template_period')
        batch_op.drop_index('ix_assigned_form_public_token')
        batch_op.drop_index('ix_assigned_form_public_active')
        batch_op.drop_index('ix_assigned_form_assigned_at')

    op.drop_table('assigned_form')
    with op.batch_alter_table('admin_action_log', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_action_user_time')
        batch_op.drop_index('ix_admin_action_type')
        batch_op.drop_index('ix_admin_action_target')
        batch_op.drop_index('ix_admin_action_risk')

    op.drop_table('admin_action_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.drop_index('ix_sector_active_order')

    op.drop_table('sector')
    op.drop_table('secretariat_regional_offices')
    op.drop_table('secretariat_divisions')
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_index('ix_resource_type')
        batch_op.drop_index('ix_resource_pub_date')
        batch_op.drop_index('ix_resource_created_at')

    op.drop_table('resource')
    with op.batch_alter_table('lookup_list', schema=None) as batch_op:
        batch_op.drop_index('ix_lookup_list_updated_at')

    op.drop_table('lookup_list')
    with op.batch_alter_table('indicator_bank', schema=None) as batch_op:
        batch_op.drop_index('ix_indicator_bank_usage_count')
        batch_op.drop_index('ix_indicator_bank_updated_at')
        batch_op.drop_index('ix_indicator_bank_type_unit')
        batch_op.drop_index('ix_indicator_bank_emergency')
        batch_op.drop_index('ix_indicator_bank_created_at')
        batch_op.drop_index('ix_indicator_bank_archived')

    op.drop_table('indicator_bank')
    with op.batch_alter_table('form_template_version', schema=None) as batch_op:
        batch_op.drop_index('ix_form_template_version_template_status')

    op.drop_table('form_template_version')
    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.drop_constraint('fk_form_template_published_version', type_='foreignkey')
        batch_op.drop_index('ix_form_template_type')
        batch_op.drop_index('ix_form_template_owned_by')
        batch_op.drop_index('ix_form_template_is_paginated')
        batch_op.drop_index('ix_form_template_created_by')

    op.drop_table('form_template')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('country')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
