"""add can explore data

Revision ID: add_can_explore_data
Revises: remove_usage_count
Create Date: 2025-11-28 03:01:52.599636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'add_can_explore_data'
down_revision = 'remove_usage_count'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists (in case of partial migration failure)
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('user')]

    if 'can_explore_data' not in columns:
        # Add column with default value for existing rows
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.add_column(sa.Column('can_explore_data', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    else:
        # Column exists but might be nullable or have null values - fix it
        # First, set default value for any null rows
        op.execute("UPDATE \"user\" SET can_explore_data = true WHERE can_explore_data IS NULL")
        # Then ensure it's NOT NULL (if it isn't already)
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.alter_column('can_explore_data',
                                existing_type=sa.Boolean(),
                                nullable=False,
                                server_default=sa.text('true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_explore_data')

    # ### end Alembic commands ###
