"""Add index on notification created_at

Revision ID: add_notif_created_at_idx
Revises: move_template_props_to_version
Create Date: 2025-12-11 22:55:09.943915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_notif_created_at_idx'
down_revision = 'move_template_props_to_version'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_is_revoked'), ['is_revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_is_used'), ['is_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_email'), ['user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reset_token_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_reset_token_user_unused', ['user_id', 'is_used', 'is_revoked'], unique=False)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_constraint('api_keys_key_hash_key', type_='unique')
        batch_op.drop_constraint('api_keys_key_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_api_keys_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    # Clean up orphaned foreign key references before adding constraints
    # This must be done before adding any foreign key constraints
    connection = op.get_bind()

    # 1. Clean up orphaned assignment_entity_status records
    connection.execute(sa.text("""
        DELETE FROM assignment_entity_status
        WHERE assigned_form_id NOT IN (SELECT id FROM assigned_form)
    """))

    # 2. Clean up orphaned form_item records with invalid indicator_bank_id
    # Set to NULL if column allows it, otherwise delete
    connection.execute(sa.text("""
        UPDATE form_item
        SET indicator_bank_id = NULL
        WHERE indicator_bank_id IS NOT NULL
        AND indicator_bank_id NOT IN (SELECT id FROM indicator_bank)
    """))

    # 3. Clean up orphaned form_item records with invalid version_id, section_id, or template_id
    connection.execute(sa.text("""
        DELETE FROM form_item
        WHERE (version_id IS NOT NULL AND version_id NOT IN (SELECT id FROM form_template_version))
           OR (section_id IS NOT NULL AND section_id NOT IN (SELECT id FROM form_section))
           OR (template_id IS NOT NULL AND template_id NOT IN (SELECT id FROM form_template))
    """))

    # 4. Clean up orphaned form_data records
    connection.execute(sa.text("""
        UPDATE form_data
        SET assignment_entity_status_id = NULL
        WHERE assignment_entity_status_id IS NOT NULL
        AND assignment_entity_status_id NOT IN (SELECT id FROM assignment_entity_status)
    """))

    connection.execute(sa.text("""
        UPDATE form_data
        SET public_submission_id = NULL
        WHERE public_submission_id IS NOT NULL
        AND public_submission_id NOT IN (SELECT id FROM public_submission)
    """))

    # 5. Clean up orphaned form_section records
    connection.execute(sa.text("""
        DELETE FROM form_section
        WHERE (template_id IS NOT NULL AND template_id NOT IN (SELECT id FROM form_template))
           OR (version_id IS NOT NULL AND version_id NOT IN (SELECT id FROM form_template_version))
           OR (page_id IS NOT NULL AND page_id NOT IN (SELECT id FROM form_page))
    """))

    # 6. Clean up orphaned form_page records
    connection.execute(sa.text("""
        DELETE FROM form_page
        WHERE (template_id IS NOT NULL AND template_id NOT IN (SELECT id FROM form_template))
           OR (version_id IS NOT NULL AND version_id NOT IN (SELECT id FROM form_template_version))
    """))

    # 7. Clean up orphaned form_template records (set user references to NULL if user doesn't exist)
    connection.execute(sa.text("""
        UPDATE form_template
        SET created_by = NULL
        WHERE created_by IS NOT NULL
        AND created_by NOT IN (SELECT id FROM "user")
    """))

    connection.execute(sa.text("""
        UPDATE form_template
        SET owned_by = NULL
        WHERE owned_by IS NOT NULL
        AND owned_by NOT IN (SELECT id FROM "user")
    """))

    connection.execute(sa.text("""
        UPDATE form_template
        SET published_version_id = NULL
        WHERE published_version_id IS NOT NULL
        AND published_version_id NOT IN (SELECT id FROM form_template_version)
    """))

    # 8. Clean up orphaned form_template_version records
    connection.execute(sa.text("""
        UPDATE form_template_version
        SET based_on_version_id = NULL
        WHERE based_on_version_id IS NOT NULL
        AND based_on_version_id NOT IN (SELECT id FROM form_template_version)
    """))

    connection.execute(sa.text("""
        DELETE FROM form_template_version
        WHERE template_id IS NOT NULL
        AND template_id NOT IN (SELECT id FROM form_template)
    """))

    # 9. Clean up orphaned template_share records
    connection.execute(sa.text("""
        DELETE FROM template_share
        WHERE template_id IS NOT NULL
        AND template_id NOT IN (SELECT id FROM form_template)
    """))

    # NOTE:
    # On PostgreSQL, a UNIQUE constraint creates a backing index with the same name.
    # Depending on historical schema state, `_assigned_entity_uc` may exist as either:
    # - a UNIQUE *constraint* (with a backing index), or
    # - a UNIQUE *index* (no constraint)
    #
    # Dropping the index directly can fail when it is owned by a constraint:
    #   psycopg2.errors.DependentObjectsStillExist: cannot drop index ... because constraint ... requires it
    #
    # Make this migration robust by dropping the constraint first (if it exists),
    # then dropping any leftover index (if it exists).
    op.execute(sa.text('ALTER TABLE assignment_entity_status DROP CONSTRAINT IF EXISTS _assigned_entity_uc'))
    op.execute(sa.text('DROP INDEX IF EXISTS _assigned_entity_uc'))

    with op.batch_alter_table('assignment_entity_status', schema=None) as batch_op:
        batch_op.create_unique_constraint('_assigned_entity_uc', ['assigned_form_id', 'entity_type', 'entity_id'])
        batch_op.create_foreign_key(None, 'assigned_form', ['assigned_form_id'], ['id'])

    with op.batch_alter_table('dynamic_indicator_data', schema=None) as batch_op:
        batch_op.drop_index('idx_dynamicindicator_data_status')

    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.drop_index('idx_formdata_assignment_formitem')
        batch_op.create_foreign_key(None, 'assignment_entity_status', ['assignment_entity_status_id'], ['id'])
        batch_op.create_foreign_key(None, 'public_submission', ['public_submission_id'], ['id'])

    with op.batch_alter_table('form_item', schema=None) as batch_op:
        batch_op.drop_index('idx_formitem_section_order')
        batch_op.drop_index('ix_form_item_version')
        batch_op.create_foreign_key(None, 'form_template_version', ['version_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'form_section', ['section_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'indicator_bank', ['indicator_bank_id'], ['id'])
        batch_op.create_foreign_key(None, 'form_template', ['template_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('form_page', schema=None) as batch_op:
        batch_op.drop_index('ix_form_page_version')
        batch_op.create_foreign_key(None, 'form_template', ['template_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'form_template_version', ['version_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('form_section', schema=None) as batch_op:
        batch_op.drop_index('ix_form_section_version')
        batch_op.create_foreign_key(None, 'form_template', ['template_id'], ['id'])
        batch_op.create_foreign_key(None, 'form_template_version', ['version_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'form_page', ['page_id'], ['id'], ondelete='CASCADE')

    # `fk_form_template_published_version` is already created by the initial migration on some installs.
    # Make this migration idempotent by dropping it first if it exists.
    op.execute(sa.text('ALTER TABLE form_template DROP CONSTRAINT IF EXISTS fk_form_template_published_version'))

    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_form_template_published_version', 'form_template_version', ['published_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
        batch_op.create_foreign_key(None, 'user', ['owned_by'], ['id'])

    with op.batch_alter_table('form_template_version', schema=None) as batch_op:
        batch_op.drop_constraint('form_template_version_based_on_version_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('form_template_version_template_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'form_template_version', ['based_on_version_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'form_template', ['template_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('repeat_group_data', schema=None) as batch_op:
        batch_op.drop_index('idx_repeatgroupdata_instance')

    with op.batch_alter_table('template_share', schema=None) as batch_op:
        batch_op.drop_constraint('template_share_template_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'form_template', ['template_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_entity_permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_user_entity_permission_user_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_entity_permissions', schema=None) as batch_op:
        batch_op.create_index('idx_user_entity_permission_user_type', ['user_id', 'entity_type'], unique=False)

    with op.batch_alter_table('template_share', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('template_share_template_id_fkey', 'form_template', ['template_id'], ['id'])

    with op.batch_alter_table('repeat_group_data', schema=None) as batch_op:
        batch_op.create_index('idx_repeatgroupdata_instance', ['repeat_instance_id'], unique=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_created_at')

    with op.batch_alter_table('form_template_version', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('form_template_version_template_id_fkey', 'form_template', ['template_id'], ['id'])
        batch_op.create_foreign_key('form_template_version_based_on_version_id_fkey', 'form_template_version', ['based_on_version_id'], ['id'])

    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_form_template_published_version', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('form_section', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_form_section_version', ['version_id'], unique=False)

    with op.batch_alter_table('form_page', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_form_page_version', ['version_id'], unique=False)

    with op.batch_alter_table('form_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_form_item_version', ['version_id'], unique=False)
        batch_op.create_index('idx_formitem_section_order', ['section_id', 'order'], unique=False)

    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('idx_formdata_assignment_formitem', ['assignment_entity_status_id', 'form_item_id'], unique=False)

    with op.batch_alter_table('dynamic_indicator_data', schema=None) as batch_op:
        batch_op.create_index('idx_dynamicindicator_data_status', ['assignment_entity_status_id'], unique=False)

    with op.batch_alter_table('assignment_entity_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_assigned_entity_uc', type_='unique')
        batch_op.create_index('_assigned_entity_uc', ['assigned_form_id', 'entity_type', 'entity_id'], unique=True)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_expires_at'))
        batch_op.create_unique_constraint('api_keys_key_id_key', ['key_id'])
        batch_op.create_unique_constraint('api_keys_key_hash_key', ['key_hash'])

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_reset_token_user_unused')
        batch_op.drop_index('ix_reset_token_expires')
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_email'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_is_used'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_is_revoked'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_created_at'))

    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
