"""Switch notifications to entity scope, remove country_id

Revision ID: notif_entity_scope
Revises: add_notif_i18n_keys
Create Date: 2025-11-23 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'notif_entity_scope'
down_revision = 'add_notif_i18n_keys'
branch_labels = None
depends_on = None


def upgrade():
    # Add new entity scope columns
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.Integer(), nullable=True))
        # Drop country_id (and any associated FK) safely within batch operation
        # Drop index on country_id if it exists (Alembic batch will handle re-creation)
        try:
            batch_op.drop_index('ix_notification_country')
        except Exception:
            # Index may not exist across environments
            pass
        try:
            batch_op.drop_constraint('notification_country_id_fkey', type_='foreignkey')
        except Exception:
            # Constraint name may be autogenerated; batch dropping column will handle it
            pass
        batch_op.drop_column('country_id')

    # Create composite index for new entity fields
    op.create_index('ix_notification_entity', 'notification', ['entity_type', 'entity_id'], unique=False)


def downgrade():
    # Remove new entity fields and reintroduce country_id
    with op.batch_alter_table('notification', schema=None) as batch_op:
        # Recreate country_id (nullable to match prior usage)
        batch_op.add_column(sa.Column('country_id', sa.Integer(), nullable=True))
        # Recreate FK to country table if present
        try:
            batch_op.create_foreign_key('notification_country_id_fkey', 'country', ['country_id'], ['id'])
        except Exception:
            # Country table may not exist in some test environments
            pass
        # Recreate index on country_id
        try:
            batch_op.create_index('ix_notification_country', ['country_id'])
        except Exception:
            pass
        # Drop entity fields
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')

    # Drop composite index
    try:
        op.drop_index('ix_notification_entity', table_name='notification')
    except Exception:
        pass
