# Security headers middleware for Flask
from flask import current_app, request, make_response
from functools import wraps

def add_security_headers(response):
    """Add comprehensive security headers to all responses.

    Note: Static files have their own cache headers set by the custom static route.
    This function preserves those cache headers and doesn't override them.
    """
    # Skip cache header modification for static files that have custom cache headers
    # Static files are handled by the custom route in app/__init__.py
    if hasattr(response, '_skip_cache_override') and response._skip_cache_override:
        # Don't modify cache headers for static files
        pass
    elif request.endpoint == 'static' or request.path.startswith('/static/'):
        # Don't modify cache headers for static files
        pass
    else:
        # For non-static files, ensure no-cache if not already set
        # This prevents caching of dynamic content
        if 'Cache-Control' not in response.headers:
            response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'

    # Prevent clickjacking
    response.headers['X-Frame-Options'] = 'DENY'

    # Prevent MIME type sniffing
    response.headers['X-Content-Type-Options'] = 'nosniff'

    # Enable XSS protection
    response.headers['X-XSS-Protection'] = '1; mode=block'

    # Strict Transport Security (HTTPS only)
    if request.is_secure:
        response.headers['Strict-Transport-Security'] = 'max-age=31536000; includeSubDomains; preload'

    # Content Security Policy
    # SECURITY: Supports both nonce-based and unsafe-inline for gradual migration
    # - Nonce-based scripts/styles: More secure, requires template updates
    # - unsafe-inline: Legacy support, can be removed after full migration

    # Generate nonce for this request (available for templates via csp_nonce())
    from app.utils.csp_nonce import get_csp_nonce
    try:
        csp_nonce = get_csp_nonce()
        nonce_directive = f"'nonce-{csp_nonce}'"
    except Exception as e:
        current_app.logger.debug("CSP nonce generation failed: %s", e)
        csp_nonce = None
        nonce_directive = ""

    # Build CSP policy with nonce support
    # STATUS: ~95-98% of templates migrated to use nonces for scripts/styles
    # IMPORTANT: When a nonce is present, browsers ignore 'unsafe-inline' completely
    # - Scripts: Use nonces (more secure) - 'unsafe-inline' removed for scripts (security active!)
    # - Styles: Keep 'unsafe-inline' (inline style attributes and JS-set styles can't use nonces)
    # 30+ templates migrated including: layout.html, form_builder.html, entry_form.html, dashboard.html,
    # notifications/center.html, admin/api_management.html, auth/login.html, tours/tours.html, and all admin templates
    # CSP hashes added for external library inline scripts that can't use nonces
    # These are dynamically generated by external libraries (jQuery, Select2, Chart.js, etc.)
    # When external libraries inject inline scripts, CSP hashes allow only those specific scripts
    script_hashes = (
        "'sha256-F2OZJCLKXjn5GkgDK82TQCGt3VAD7pAvv2GegMmBmmA=' "  # External library inline script 1
        "'sha256-C0POBvuIg2WsFkKXuy5NW4X27PXkxKrkaQL0AjxA/B8=' "  # External library inline script 2
        "'sha256-eRf/6o7h063u1aRHq9JazzrFoegwHCJN/dFqqZg7oF0=' "  # External library inline script 3
        "'sha256-4go2tWGJE+CNuqNpl48Yv+bO4uu+BQJh1MJF3yTjhl8=' "  # External library inline script 4
        "'sha256-Y/4W14eTM3Az3L4dOeJ6tK2FFZ+wZxp7ssM38MBKM2g=' "  # External library inline script 5
        "'sha256-dt/ya86/s8LgFk2v8XZkKpeGcfwvFHR3ivK+gBEVm64=' "  # External library inline script 6
        "'sha256-9plDW+xe6iwb+kc2Ab2H1JEg2Z7f2/5tGt6Ovl5ojFE=' "  # Plugin settings inline script 1
        "'sha256-ewJJ2tQuYLmjU/myxACs+VuEoGqmyJwcCEYdr+AuMac=' "  # Plugin settings inline script 2
        "'sha256-iNLi1rYoOeNI8CEXwy6NnxglbQ3BjdJZbgZHvuY89wA=' "  # Plugin settings inline script 3
        "'sha256-xG5vOuTJfko1kfw3c6cQOiOXhaZxr2Yhc5uF1ybVo+c=' "  # Plugin settings inline script 4
        "'sha256-ofVqu4ZzAuGbayuRZeenPtqaKeG7wyBnn5XRT9+Pyew='"   # Plugin settings inline script 5
    )
    script_src = f"'self' {nonce_directive} {script_hashes} https://cdnjs.cloudflare.com https://code.jquery.com https://cdn.jsdelivr.net https://unpkg.com https://www.gstatic.com".strip()
    style_src = f"'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://cdn.jsdelivr.net https://fonts.googleapis.com https://unpkg.com https://www.gstatic.com".strip()

    csp_policy = (
        f"default-src 'self'; "
        f"script-src {script_src}; "
        f"style-src {style_src}; "
        "img-src 'self' data: blob: https:; "
        "font-src 'self' data: https://cdnjs.cloudflare.com https://fonts.gstatic.com; "
        "connect-src 'self' https://unpkg.com https://www.gstatic.com https://cdn.jsdelivr.net https://nominatim.openstreetmap.org https://ipapi.co; "
        "frame-ancestors 'none'; "
        "base-uri 'self'; "
        "form-action 'self'"
    )
    response.headers['Content-Security-Policy'] = csp_policy

    # Referrer Policy
    response.headers['Referrer-Policy'] = 'strict-origin-when-cross-origin'

    # Permissions Policy (formerly Feature Policy)
    response.headers['Permissions-Policy'] = (
        "geolocation=(self), "
        "microphone=(), "
        "camera=(), "
        "payment=(), "
        "usb=(), "
        "magnetometer=(), "
        "gyroscope=(), "
        "fullscreen=(self), "
        "sync-xhr=()"
    )

    # Remove server header
    response.headers.pop('Server', None)

    return response

def init_security_headers(app):
    """Initialize security headers middleware."""
    app.after_request(add_security_headers)
